import { portfolio } from "@/data/portfolio";
import { Icon } from "@/components/Icon";
import { Reveal } from "@/components/Reveal";

function Heading({ kicker, title, body }: { kicker: string; title: string; body?: string }) {
  return <div className="mb-12 max-w-2xl"><p className="section-kicker">{kicker}</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.05em] text-white sm:text-5xl">{title}</h2>{body && <p className="mt-5 leading-7 text-slate-400">{body}</p>}</div>;
}

export function About() {
  return <section id="about" className="section-pad"><div className="container-x grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><Reveal><Heading kicker="01 / About me" title="Curious by default. Practical by design."/><div className="flex items-center gap-3 font-mono text-xs text-slate-500"><span className="h-px w-8 bg-violet-300"/>{portfolio.role}</div></Reveal><Reveal><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[.025] p-6 sm:col-span-2"><p className="text-lg leading-8 text-slate-300">I&apos;m a CSE student at <span className="text-white">{portfolio.university}</span>, learning by building and by understanding how software works beneath the surface. My current path sits at the intersection of web development, software engineering fundamentals, and academic curiosity.</p></div><div className="rounded-2xl border border-white/10 bg-[#0d1324] p-6"><p className="font-mono text-[10px] uppercase tracking-widest text-violet-200">What I build</p><p className="mt-5 text-sm leading-7 text-slate-400">Interfaces, coursework projects, desktop applications, and practical systems that turn concepts into something tangible.</p></div><div className="rounded-2xl border border-cyan-300/15 bg-cyan-300/[.04] p-6"><p className="font-mono text-[10px] uppercase tracking-widest text-cyan-200">Currently exploring</p><div className="mt-5 flex flex-wrap gap-2">{portfolio.interests.slice(0, 5).map(item => <span key={item} className="rounded-full border border-cyan-300/15 px-3 py-1.5 text-xs text-slate-300">{item}</span>)}</div></div></div></Reveal></div></section>;
}

export function Skills() {
  return <section id="skills" className="section-pad border-y border-white/[.06] bg-[#0a0e1b]"><div className="container-x"><Heading kicker="02 / Skills & technologies" title="A growing toolkit, mapped to the work." body="A practical view of the languages, concepts, and tools I am using or learning—without artificial proficiency scores."/><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{portfolio.skills.map((skill, index) => <Reveal key={skill.title} delay={index * .04}><article className="skill-card h-full rounded-2xl border border-white/10 bg-[#0d1324] p-6 transition hover:-translate-y-1 hover:border-violet-300/35"><div className="flex items-start justify-between gap-4"><span className="flex h-10 w-10 items-center justify-center rounded-xl border border-violet-300/20 bg-violet-300/10 text-violet-200"><Icon name={skill.icon}/></span><span className="font-mono text-[10px] text-slate-600">0{index + 1}</span></div><h3 className="mt-6 text-lg font-medium text-white">{skill.title}</h3><p className="mt-3 min-h-12 text-sm leading-6 text-slate-500">{skill.description}</p><div className="mt-6 flex flex-wrap gap-2">{skill.items.map(item => <span key={item} className="rounded-lg border border-white/10 bg-white/[.035] px-2.5 py-1.5 font-mono text-[11px] text-slate-300">{item}</span>)}</div></article></Reveal>)}</div></div></section>;
}
