"use client";

import { FormEvent } from "react";
import { ArrowUpRight } from "lucide-react";
import { portfolio } from "@/data/portfolio";
import { Icon } from "@/components/Icon";
import { Reveal } from "@/components/Reveal";

const Heading = ({ kicker, title, body }: { kicker: string; title: string; body?: string }) => <div className="mb-12 max-w-2xl"><p className="section-kicker">{kicker}</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.05em] text-white sm:text-5xl">{title}</h2>{body && <p className="mt-5 leading-7 text-slate-400">{body}</p>}</div>;

export function CurrentlyBuilding() {
  const items = portfolio.currentlyBuilding;
  return <section className="section-pad border-y border-white/[.06] bg-[#080d1b]"><div className="container-x"><Heading kicker="06 / In progress" title="Currently Building" body="A small view of the work and questions currently shaping my learning path."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{items.map((item, index) => <Reveal key={item.title} delay={index * .04}><article className="building-card group h-full rounded-2xl border border-white/10 bg-white/[.025] p-5 transition hover:-translate-y-1 hover:border-cyan-300/30"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl border border-cyan-300/20 bg-cyan-300/10 text-cyan-200 transition group-hover:scale-105"><Icon name={item.icon}/></span><span className="rounded-full border border-cyan-300/15 px-2.5 py-1 font-mono text-[10px] uppercase tracking-wider text-cyan-200">{item.status}</span></div><h3 className="mt-8 text-base font-medium text-white">{item.title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{item.text}</p></article></Reveal>)}</div></div></section>;
}

export function EducationJourney() {
  return <><section className="section-pad"><div className="container-x grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><Reveal><Heading kicker="05 / Education" title="Grounded in computer science." body="An academic path built around fundamentals, projects, and a willingness to keep learning."/></Reveal><Reveal><div className="relative rounded-2xl border border-violet-300/20 bg-[#0d1324] p-7 sm:p-9"><div className="absolute left-0 top-10 h-16 w-1 rounded-r-full bg-violet-300"/><div className="flex items-start justify-between gap-6"><div><p className="font-mono text-xs uppercase tracking-widest text-violet-200">Current · Bachelor</p><h3 className="mt-5 text-2xl font-medium text-white">Computer Science & Engineering</h3><p className="mt-3 text-slate-300">{portfolio.university}</p></div><Icon name="graduation" size={30}/></div><div className="mt-10 grid gap-3 border-t border-white/10 pt-5 text-sm text-slate-400 sm:grid-cols-2"><span>Relevant areas</span><span className="text-slate-200 sm:text-right">Web · OOP · Algorithms · Research</span><span>Current status</span><span className="text-slate-200 sm:text-right">Actively learning and building</span></div></div></Reveal></div></section><section id="journey" className="section-pad border-y border-white/[.06] bg-[#0a0e1b]"><div className="container-x grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><Reveal><Heading kicker="06 / The journey" title="Learning & Building Journey" body="No invented job titles—just the real progression of concepts, projects, and questions I am working through."/></Reveal><div className="relative border-l border-white/15 pl-7">{portfolio.journey.map((item, index) => <Reveal key={item.title} delay={index * .04}><div className="relative mb-9 last:mb-0"><span className="absolute -left-[33px] top-1 h-2.5 w-2.5 rounded-full border-2 border-violet-200 bg-[#0a0e1b]"/><p className="font-mono text-xs uppercase tracking-widest text-violet-200">{item.year}</p><h3 className="mt-2 text-lg font-medium text-white">{item.title}</h3><p className="mt-2 max-w-lg text-sm leading-6 text-slate-500">{item.text}</p></div></Reveal>)}</div></div></section></>;
}

export function Achievements() {
  return <section id="achievements" className="section-pad"><div className="container-x"><Heading kicker="07 / Honors" title="Achievements & Certifications" body="A small, verified record of academic and research milestones. No invented credentials or statistics."/><div className="grid gap-5 md:grid-cols-2">{portfolio.achievements.map((item, index) => { const featured = index === 1; return <Reveal key={item.title}><article className={`achievement-card h-full rounded-2xl border p-7 transition hover:-translate-y-1 ${featured ? "achievement-priority group" : "border-white/10 bg-[#0d1324] hover:border-violet-300/40"}`}><div className="relative z-10 flex items-start justify-between gap-4"><span className={`flex h-12 w-12 items-center justify-center rounded-2xl transition group-hover:scale-105 ${featured ? "achievement-award-icon" : "border border-violet-300/25 bg-violet-300/10 text-violet-100"}`}><Icon name="award"/></span>{featured ? <span className="achievement-badge rounded-full px-3 py-1.5 font-mono text-[10px] uppercase tracking-widest">Dean&apos;s Award</span> : <span className="rounded-full border border-white/10 px-3 py-1 font-mono text-[10px] uppercase tracking-wider text-slate-500">{item.category}</span>}</div><h3 className={`relative z-10 mt-7 text-xl font-medium leading-tight ${featured ? "text-white sm:text-2xl" : "text-white"}`}>{featured ? <>Dean&apos;s Award for <span className="achievement-title-accent">Academic Excellence</span></> : item.title}</h3><p className={`relative z-10 mt-3 text-sm leading-6 ${featured ? "text-amber-50/80" : "text-slate-400"}`}>{item.issuer}</p><div className="relative z-10 mt-7 flex items-center justify-between gap-4 border-t border-white/10 pt-4"><span className={featured ? "achievement-year rounded-full px-3 py-1 font-mono text-sm font-bold" : "font-mono text-xs text-cyan-200"}>{item.date}</span><a href={portfolio.linkedin} target="_blank" rel="noreferrer" className={`focus-ring inline-flex items-center gap-1 rounded-lg px-3 py-2 text-xs font-semibold transition hover:-translate-y-0.5 ${featured ? "achievement-credential" : "bg-violet-200 text-slate-950 hover:bg-white"}`}>View Credential <ArrowUpRight size={13}/></a></div></article></Reveal>; })}</div></div></section>;
}

export function ResearchLearningServices() {
  return <><section id="research" className="section-pad border-y border-white/[.06] bg-[#0a0e1b]"><div className="container-x"><Heading kicker="08 / Research & interests" title="Questions worth spending time on." body="I am interested in the space where solid computer science foundations meet useful products and meaningful research."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{portfolio.researchTopics.map((item, index) => <Reveal key={item.title} delay={index * .04}><article className="group h-full rounded-2xl border border-white/10 bg-[#0d1324] p-6 transition hover:-translate-y-1 hover:border-cyan-300/30"><span className="flex h-10 w-10 items-center justify-center rounded-xl border border-cyan-300/20 bg-cyan-300/10 text-cyan-200 transition group-hover:scale-105"><Icon name={item.icon}/></span><h3 className="mt-7 text-lg font-medium text-white">{item.title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{item.text}</p></article></Reveal>)}</div></div></section><section id="learning" className="section-pad"><div className="container-x"><Heading kicker="09 / In progress" title="Currently Learning" body="A visible learning queue—progress measured by practice and understanding, not made-up percentages."/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{portfolio.learning.map((item, index) => <Reveal key={item}><div className="group rounded-xl border border-white/10 bg-white/[.025] p-5 transition hover:border-violet-300/35"><div className="flex items-center justify-between"><span className="font-mono text-xs text-violet-200">0{index + 1}</span><span className="h-1.5 w-1.5 rounded-full bg-cyan-300 opacity-60 group-hover:opacity-100"/></div><p className="mt-8 text-sm font-medium text-slate-200">{item}</p></div></Reveal>)}</div></div></section><section id="services" className="section-pad border-y border-white/[.06] bg-[#0a0e1b]"><div className="container-x"><Heading kicker="10 / What I can build" title="Useful software, built at the right level." body="Student and junior-developer capabilities focused on clear scope, thoughtful interfaces, and steady learning."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{portfolio.services.map((item, index) => <Reveal key={item.title} delay={index * .04}><article className="rounded-2xl border border-white/10 bg-[#0d1324] p-6 transition hover:-translate-y-1 hover:border-violet-300/35"><span className="font-mono text-xs text-violet-200">0{index + 1}</span><h3 className="mt-12 text-lg font-medium text-white">{item.title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{item.text}</p></article></Reveal>)}</div></div></section></>;
}

export function Contact() {
  const submit = (event: FormEvent<HTMLFormElement>) => event.preventDefault();
  return <section id="contact" className="contact-section section-pad text-white"><div className="container-x grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="font-mono text-xs uppercase tracking-widest text-violet-200">11 / Contact</p><h2 className="mt-5 text-4xl font-semibold leading-[.98] tracking-[-.06em] text-white sm:text-6xl">Let&apos;s build<br/>something useful.</h2><p className="mt-6 max-w-md leading-7 text-slate-400">Have an opportunity, a project idea, or a question about what I&apos;m learning? I&apos;d be happy to hear from you.</p><div className="mt-8 space-y-3 text-sm"><a href={portfolio.github} target="_blank" rel="noreferrer" className="flex items-center gap-3 text-violet-100 transition hover:text-violet-200 hover:underline"><Icon name="github" size={17}/>github.com/Tashin90</a><a href={portfolio.linkedin} target="_blank" rel="noreferrer" className="flex items-center gap-3 text-cyan-100 transition hover:text-cyan-200 hover:underline"><Icon name="linkedin" size={17}/>LinkedIn profile</a><a href={portfolio.email} className="flex items-center gap-3 text-teal-100 transition hover:text-teal-200 hover:underline"><Icon name="mail" size={17}/>{portfolio.emailLabel}</a></div></div><form onSubmit={submit} className="rounded-2xl border border-white/10 bg-[rgba(8,11,24,.88)] p-6 text-white shadow-2xl sm:p-8"><p className="font-mono text-xs uppercase tracking-widest text-violet-200">Send a note / TODO: connect email service</p><div className="mt-7 grid gap-5 sm:grid-cols-2">{[["Name","name","text"],["Email","email","email"],["Subject","subject","text"]].map(([label,name,type], index) => <label key={name} className={index === 2 ? "sm:col-span-2" : ""}><span className="mb-2 block text-xs text-slate-500">{label}</span><input required name={name} type={type} className="focus-ring w-full rounded-xl border border-white/10 bg-[#0b1020] px-3 py-3 text-sm text-slate-100 outline-none transition placeholder:text-slate-600 focus:border-violet-300/60 focus:shadow-[0_0_20px_rgba(139,92,246,.14)]"/></label>)}<label className="sm:col-span-2"><span className="mb-2 block text-xs text-slate-500">Message</span><textarea required name="message" rows={5} className="focus-ring w-full resize-y rounded-xl border border-white/10 bg-[#0b1020] px-3 py-3 text-sm text-slate-100 outline-none transition placeholder:text-slate-600 focus:border-violet-300/60 focus:shadow-[0_0_20px_rgba(139,92,246,.14)]"/></label></div><button className="mt-6 inline-flex items-center gap-2 rounded-xl border border-violet-300/25 bg-gradient-to-r from-violet-500/80 via-blue-500/75 to-cyan-500/70 px-5 py-3 text-sm font-semibold text-white shadow-[0_0_26px_rgba(99,102,241,.2)] transition hover:brightness-110">Send message <ArrowUpRight size={16}/></button></form></div></section>;
}

export function Footer() { return <footer className="border-t border-white/10 bg-[#070a13] py-8"><div className="container-x flex flex-col justify-between gap-5 text-xs text-slate-500 sm:flex-row"><div><p className="font-medium text-slate-200">{portfolio.name}</p><p className="mt-1">{portfolio.role}</p></div><div className="flex flex-wrap gap-x-5 gap-y-2"><a href="#home" className="hover:text-white">Home</a><a href="#projects" className="hover:text-white">Projects</a><a href={portfolio.github} target="_blank" rel="noreferrer" className="hover:text-white">GitHub</a><a href={portfolio.linkedin} target="_blank" rel="noreferrer" className="hover:text-white">LinkedIn</a><a href={portfolio.email} className="hover:text-white">Email</a><a href={portfolio.resume} className="hover:text-white">Resume</a></div><p>© {new Date().getFullYear()} · Built with curiosity.</p></div></footer>; }
